
public class Two {
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    // Considering starting values 1, 2
    // Sum of even values fibonacci whole value < 4Million
    public static void main(String[] args) {

    }

}
